config/routes.rb
Rails.application.routes.draw do
  resources :leads #ici pr relier la news a l'app rails
  resources "contacts", only: [:new, :create]
  get 'static/pages'

  root'static#index'
  get 'projets' => 'static#projets'
  get 'contact' => 'static#contact'
  get 'oxyghem' => 'static#oxyghem'
  get 'simplon' => 'static#simplon'
  get 'damart' => 'static#damart'
  get 'actionboxe' => 'static#actionboxe'
  get 'identity' => 'static#identity'
  get 'nobleart' => 'static#nobleart'
  get 'sens' => 'static#sens'
  get 'sucess' => 'static#sucess'
  get 'taillefinefiz' => 'static#taillefinefiz'

  
  

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "contact@coloredcloud.fr",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/lead.rb
class Lead < ActiveRecord::Base
	#want to valid the presense of field
	validates :email, :statut, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
  	@lead = Lead.new
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Merci pour votre message ! Je vous repond aussi tôt!'
    else
      flash.now[:error] = 'Erreur message'
      render :new
    end
    end
    end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
def create
	#capture the informations from the params save it to the lead
	@lead = Lead.new lead_params
	#make sur to save it 
		
	if @lead.save
		
	#it redirect to root_path
	#ici message notice pour la newsletter style bootstrap style css dans le container 
	    redirect_to root_path, notice: "Vous êtes maintenant inscrit à la newsletter !" 
	    
	#ici quand message missing template eror
    else
    	redirect_to root_path, alert: "Erreur...recommencez !" #ici message alerte style bootstrap pour la newsletter
    end

end

private

  def lead_params
	params.require(:lead).permit(:email, :statut) #strong parameters
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def pages
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
               concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
                        concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
                        concat content_tag(:span, 'Close', class: 'sr-only')
               end)
               concat message
      end)
    end
    nil
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>


</body>
</html>

app/views/contacts/new.html.erb
<div class="container">
<div align="center">
    <div class="contact">
  <h5>Laissez moi un message</h5>

  <%= simple_form_for @contact, :url => contacts_path do |f| %>
    <%= f.input :name, :required => true %>
    <%= f.input :email, :required => true %>
    <%= f.input :message, :as => :text, :required => true %>
    <div class= "hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
    </div>
    <div>
      </br>
      <%= f.button :submit, 'Envoyer', :class=> "btn btn-primary" %>
    </div>
  <% end %>
</div>
</div>
</div>

<!-- ///////////////////////////////////// FOOTER ///////////////////////////////-->
<div class="container">
    <div id="conteneur_footer">
    <div class="row">

        <div class="col-md-12 col-sm-12 col-xs-12 banner_footer">  
            <h4>footer</h4>
        
        </div><!--#footer -->

    <div class="row">
            <div class="col-md-4 col-sm-4 col-xs-4 footer"> 
                    <ul id="contact">
                        <li class="tel">06 50 07 59 52</li>
                        <li class="mail">contact@coloredcloud.fr</li>
                    </ul>
            </div>

            <div class="col-md-4 col-sm-4 col-xs-4 footer">
                        
            </div>

             <div class="col-md-4 col-sm-4 col-xs-4 footer">
                        <ul id="menu_footer">
                            
                            <li><%=link_to 'Home', root_path%></li>
                            <li><%=link_to 'projets', projets_path%></li>
                            <li><%=link_to 'contact', contacts_path%></li>
                            <li><a href="http://www.coloredcloud.fr" target="_blank">Blog</a></li>
                        </ul>
            </div>

         </div><!-- .bloc_footer -->
    </div><!--#footer -->
</div><!--#container_footer -->
</div><!-- #container -->

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ccprosite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "style"%>
  <%= stylesheet_link_tag "bootstrap"%>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div id="find my mechanics in application_helper  _B.s._" class="message"> <%= flash_messages %></div>
  <!-- ici on met les flash message pr la newsletter -->
 

    <!-- ///////////////////////////// container header ////////////////// -->

    <div class="row">
         <div class="col-md-12 col-sm-10 col-xs-12 header">

            <div id="logo">
                    <a href="">
                      
                <!-- ici je peux mettre une autre version du logo pr le format portrait un logo vertical -->
                    </a>
                </div><!-- #logo -->

            <div id="menu">
                <nav class="navbar navbar-default">
                    <ul>

                        <li><%=link_to 'Home', root_path%></li>
                        <li><%=link_to 'projets', projets_path%></li>
                        <li><%=link_to 'contact', contact_path%></li>

                       <!-- <li>
                            <a href="#" id="reseaux">Social</a>
                            <ul class="sub">
                                <li><a href="" target="_blank" id="twitter"></a></li>
                            </ul>                               
                        </li> -->
                    </ul>
                </nav>
             </div><!-- #menu -->
        </div><!-- #header -->
    </div><!-- #row-->
    </div><!-- #row-->

<%= yield %>




</body>
</html>

app/views/leads/create.js.erb
<% if @lead.errors.any? %>
alert("please fill out the entire form")
<% else %>
$("#new_lead").hide()
<% end %>